version: 2
registries:
  maven-artifactory:
    type: maven-repository
    url: https://maven.bjoggis.com
    username: ${{secrets.REPOSILITE_USERNAME}}
    password: ${{secrets.REPOSILITE_PASSWORD}}
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    registries:
      - maven-artifactory
    schedule:
      interval: "daily"
