name: Build latest master and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.11.0
        with:
          java-version: 21
          java-distribution: liberica
          checkout-persist-credentials: true
          settings-servers: |
            [{
                "id": "reposilite-releases",
                "username": "${{ secrets.REPOSILITE_USERNAME }}",
                "password": "${{ secrets.REPOSILITE_PASSWORD }}"
            },
            {
                "id": "reposilite-snapshots",
                "username": "${{ secrets.REPOSILITE_USERNAME }}",
                "password": "${{ secrets.REPOSILITE_PASSWORD }}"
            }]
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with Maven
        run: mvn spring-boot:build-image -Pnative

      - name: Find version
        run: echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Push Images to Docker Registry
        run: docker push -a bjoggis/authorization-server
      - name: Create and push manifest
        run: |
          docker manifest create bjoggis/authorization-server:v${{ env.PROJECT_VERSION }} bjoggis/authorization-server:v${{ env.PROJECT_VERSION }}-x86_64
          docker manifest push bjoggis/authorization-server:v${{ env.PROJECT_VERSION }}
          docker manifest create bjoggis/authorization-server:latest bjoggis/authorization-server:v${{ env.PROJECT_VERSION }}-x86_64
          docker manifest push bjoggis/authorization-server:latest